version: '3.7'
services:
  worker-management:
    image: harbor.ittim-online.com/avis_public/worker_management:latest
    restart: always
    stop_grace_period: 5m
    environment:
      - NATS_PASS=${NATS_PASS}
      - MANAGEMENT_SERVER=${MANAGEMENT_SERVER}
      - PORT=${PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - STREAMS_VOLUME=streamsVolume
      - USE_MOUNT_FOR_TIMESHIFT=true
      - TIMESHIFT_MOUNT=/opt/AVIS_Worker/data/timeshift/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/management:/opt/data
      - ./data/vod/movies:/opt/vod/movies
      - streamsVolume:/opt/streams
      - ./data/timeshift/:/opt/timeshift/
    ports:
      - "${PORT}:${PORT}"
      - "${CLIENT_PORT}:80"

  multicast_proxy:
    image: harbor.ittim-online.com/avis_public/worker_multicast_proxy:latest
    restart: always
    network_mode: "host"
    environment:
      - MANAGEMENT_SERVER=${MANAGEMENT_SERVER}
    volumes:
      - ./data/management:/opt/data
      
  nats:
    image: nats
    restart: always
    command: --user root --pass ${NATS_PASS} -m 8222
    environment:
      - NATS_PASS=${NATS_PASS}

  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always

networks:
  default:
    name: avis
    external: true

volumes:
  streamsVolume:
    external: true
